config/routes.rb
Xmascard::Application.routes.draw do
  devise_for :users

  get 'tags/:tag', to: 'cards#index', as: :tag

  resources :cards do
    member do
      get :back
    end
    collection do 
      get :list
    end
  end

  root :to => 'cards#index'

end

app/models/card.rb
class String
  def is_year?
    self.match(/^[12][0-9]{3}$/)
  end
end

class Card < ActiveRecord::Base
  attr_accessible :address, :message, :name, :frontimg, :backimg, :frontimg_file_name, :frontimg_content_type, :frontimg_file_size, :frontimg_updated_at, :backimg_file_name, :backimg_content_type, :backimg_file_size, :backimg_updated_at, :original_filename, :year_list, :tag_list
  attr_reader :DEFAULT_IMAGE_FOLDER
  
  has_attached_file :frontimg, 
    :styles => { :full => "600x600>", :medium => "300x300>", :thumb => "100x100>" },
    :storage => :s3,
    :path => "/frontimg/:style/:filename",
    :s3_credentials => "#{::Rails.root.to_s}/config/s3.yml"
  
  has_attached_file :backimg, 
    :styles => { :full => "600x600>", :medium => "300x300>", :thumb => "100x100>" },
    :storage => :s3,
    :path => "/backimg/:style/:filename",
    :s3_credentials => "#{::Rails.root.to_s}/config/s3.yml"
  DEFAULT_IMAGE_FOLDER = "/Users/ezraball/Documents/xmas_postcard_pics"
  
  acts_as_taggable_on :years, :tags
  
  validates :frontimg, :attachment_presence => true
  before_create :set_fingerprint
  before_save :set_name_if_blank
  
  
  def self.load_dir_of_images(dirname)
    startdir = Dir.pwd
    Dir.chdir(dirname)
    find_front_images.each do |filename|
      c = Card.find_by_original_filename(filename)
      unless c
        Card.create_from_frontimg(filename) 
      end
    end
    Dir.chdir(startdir)
  end
    
  def self.create_from_frontimg(filename)
    f = File.new(filename)
    c = Card.create(:frontimg => f, :original_filename => filename)
    c.tag_from_original_filename
    if bf = get_backimg(f)
      c.backimg = bf
      bf.close
    end
    c.save
    c
    f.close
  end
  
  def tag_from_original_filename
    if self.original_filename
      tags = self.original_filename.split("/")[0..-2]
      self.year_list = (self.year_list + tags.select{|t| t.is_year?}).flatten.join(",")
      self.tag_list = (self.tag_list + tags.reject{|t| t.is_year?}).flatten.join(",")
    end
  end
  
  def push_to_remote
    rc = RemoteCard.new
    self.attributes.each_pair do |key,value|
      rc.send("#{key}=",value)
    end
    rc.year_list = self.year_list
    rc.tag_list = self.tag_list
    rc.save
  end
  
  def set_name_if_blank
    (self.name = Card.guess_name(self.frontimg_file_name)) if self.name.blank?
  end
  
  def set_fingerprint    
    self.fingerprint = make_fingerprint
  end
  
  def self.find_front_images
    Dir.glob("**/*Front.{jpg,jpeg}")
  end
  def make_fingerprint
    "#{frontimg_file_size}-#{name}"
  end
  
  
  def next_card
    Card.where("id > #{self.id}").order(:id).first
  end
  def previous_card
    Card.where("id < #{self.id}").order("id desc").first
  end
  

  private
  
  def self.get_backimg(frontfile)
    fname = guess_backimg_name(frontfile.path)
    if fname != frontfile.path && File.exists?(fname)
      File.new(fname)
    end
  end
  
  def self.guess_backimg_name(frontimg_name)
    frontimg_name.gsub('Front','Back')
  end
  
  def self.guess_name(frontimg_name)
    frontimg_name.split("/").last.gsub("_Front",'').gsub('Back','').gsub('_',' ').gsub('.jpg','').gsub('.jpeg','').titlecase
  end
    
end

app/models/remote_card.rb
class RemoteCard < ActiveResource::Base  
  self.site = "http://xmascard.herokuapp.com/"
  self.element_name = "card"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  skip_before_filter :authenticate_user!, :only => [:new, :update, :create]
  
  
  # GET /cards
  # GET /cards.json
  def index
    @style ||= 'thumb'
    setup_index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cards }
    end
  end
  
  def list
    @style = 'list'
    setup_index
    render action: :index
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card = Card.find(params[:id])
    @main_image_method = 'frontimg'
    @tiny_image_method = 'backimg'
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
    end
  end

  def back
    @card = Card.find(params[:id])
    @main_image_method = 'backimg'
    @tiny_image_method = 'frontimg'

    respond_to do |format|
      format.html {
        render template: 'cards/show'
      }# show.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/new
  # GET /cards/new.json
  def new
    @card = Card.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/1/edit
  def edit
    @card = Card.find(params[:id])
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(params[:card])

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render json: @card, status: :created, location: @card }
      else
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    @card = Card.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end
  
  protected
  def setup_index
    if params[:fingerprint]
      @card = Card.where(:fingerprint => params[:fingerprint])
    elsif params[:tag]
      @cards = Card.tagged_with(params[:tag])
    else
      @cards = Card.where(" 1 = 1 ")
    end
    @cards = @cards.paginate(:page => params[:page], :per_page => 20)    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
  def linked_tag_list(lst)
    raw lst.map{|y| link_to(y, tag_path(y), :class => :label)}.join(" ")
  end
  
  def linked_tag_list_with_counts(lst)
    raw lst.map{|y| link_to("#{y} (#{y.count})", tag_path(y.name), :class => :label)}.join(" ")
  end
  
  def glyph(name)
    "#{name}<i class=\"icon-#{name}\"></i>".html_safe
  end
end

app/views/cards/_form.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="span6">
			<%= simple_form_for @card, :html => { :class => 'form-horizontal', :style => "width:100%;", :multipart => true } do |f| %>
			  <%= f.input :name %>
			  <%= f.input :year_list %>
			  <%= f.input :tag_list %>
			  <%= f.input :address %>
			  <%= f.input :message %>
			  <%= f.input :frontimg, :as => :file %>
			  <%= f.input :backimg, :as => :file %>
			  <div class="form-actions">
			    <%= f.button :submit, :class => 'btn-primary' %>
			    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
			                cards_path, :class => 'btn' %>
			  </div>
			<% end %>
		</div>
		
		<div class="span6">
			<div class="clearfix">
				<br>
			</div>
		    <%= image_tag @card.frontimg.url(:full) %>
			<hr>
		    <%= image_tag @card.backimg.url(:full) %>
		</div>
	</div>
</div>

app/views/cards/_list_view.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Cards</th>
	  <th>Front</th>
	  <th>Tags</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td>
			<%= link_to card.name, card %>
		</td>
		<td>
        	<%= link_to(image_tag(card.frontimg.url(:thumb)), card) %>
		</td>
		<td>
			Years: <%= linked_tag_list(card.year_list) %><br>
			Tags: <%= linked_tag_list(card.tag_list) %>
		</td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_card_path(card), :class => 'btn btn-large btn-primary', :style => "margin-right:15px;" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cards/_pagination.html.erb
<div id="navigation">
	<div class="row-fluid">
		<div class="span2">
			<span class="badge badge-info"><%= @cards.count %></span>  Cards
		</div> 
	    <div class="span4">
	  	  <%= will_paginate @cards %>
	    </div>
		<div class="span6">
			<% if params[:tag] %>
				<%= content_tag(:span, "Tagged to: <span class=\"label\">#{params[:tag]}</span>".html_safe, :class => 'pull-left') %> <%= link_to 'x', '/' %>
			<% else %>
				<% sep = '' %>
				<div>Years: <%= linked_tag_list_with_counts(Card.year_counts[0..10]) %> more...</div>
				<div>Tags: <%= linked_tag_list_with_counts(Card.tag_counts.reverse[0..10]) %> more...</div>
				
				<div class="hidden">Years: <%= linked_tag_list_with_counts(Card.year_counts) %></div>
				<div class="hidden">Tags: <%= linked_tag_list_with_counts(Card.tag_counts.reverse) %></div>				
			<% end %>
		</div>
	</div>
</div>

app/views/cards/_thumb_view.html.erb
<% @cards.each do |card| %>
	<div class="minicard pull-left">
		<%= link_to(image_tag(card.frontimg.url(:medium), :class => 'img-polaroid', alt: card.name, style: 'max-height:188px;'), card, title: "#{card.name} (#{card.year_list.join('')})", data: {toggle: 'tooltip', placement: 'top', content: (card.year_list + card.tag_list).flatten.compact.join(", "), trigger: 'hover'}, class: 'bob') %>
	</div>
<% end %>
<script>
$('.bob').tooltip();
</script>
<hr class="clearfix" style="clear:both;">

app/views/cards/edit.html.erb
<%- model_class = Card -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cards/index.html.erb
<div class="page-header">
  <h1>Cards</h1>
</div>

<%= render :partial => 'pagination' %>

<div class="row">
	<div class="span8">
		&nbsp;
	</div>
	<div class="span4">
		<%= link_to_unless('thumb' == @style, "Thumbnail view", cards_path) %> |
		<%= link_to_if('thumb' == @style, "List view", list_cards_path) %> 
	</div>
</div>

<div id="cards">
	<%= render :partial => "#{@style}_view" %>
</div>



<%= render :partial => 'pagination' %>


<%= link_to t('.new', :default => t("helpers.links.new")),
            new_card_path,
            :class => 'btn btn-primary' %>

app/views/cards/new.html.erb
<%- model_class = Card -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cards/show.html.erb
<%- model_class = Card -%>
<div class="row">
	<div class="span6">
	    <%= image_tag @card.send(@main_image_method).url(:full) %>
	</div>
	<div class="span6">
		<div class="page-header">
		  <h1><%= @card.name %></h1>
		</div>

		
		<div class="tags">
			Year: <%= linked_tag_list(@card.year_list) %><br>
			Tags: <%= linked_tag_list(@card.tag_list) %>
		</div>
		
		<% if 'backimg' == @main_image_method %>
			<%= link_to(image_tag(@card.frontimg.url(:thumb)),card_path(@card)) %>
		<% else %>
			<%= link_to(image_tag(@card.backimg.url(:thumb)),back_card_path(@card)) %>
		<% end %>
		
		
		<div class="form-actions">
			<div class="pull-left">
				<%= (link_to "&larr; Previous".html_safe, @card.previous_card, :class => 'btn btn-small') if @card.previous_card %>
				<%= (link_to "Next &rarr;".html_safe,@card.next_card, :class => 'btn btn-small') if @card.next_card %>
				<%= link_to "Up &uarr;".html_safe,cards_path, :class => 'btn btn-small', :style => "margin:0px 30px;" %>
			</div>
			
			<div class="pull-right" style="padding-left:50px;border-left:1px solid #ccc;">
	  		  <%= link_to t('.edit', :default => t("helpers.links.edit")),
	  		              edit_card_path(@card), :class => 'btn btn-large btn-primary', :style => "margin-right:15px;"  %>
	  		  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
	  		              card_path(@card),
	  		              :method => 'delete',
	  		              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
	  		              :class => 'btn btn-danger btn-mini' %>
			</div>
		</div>
		
		
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Xmascard" %></title>
    <%= csrf_meta_tags %>
	<link href='http://fonts.googleapis.com/css?family=Lustria|Open+Sans:300,700' rel='stylesheet' type='text/css'>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
	
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid pull-left" >
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Terri's Christmas Postcards</a>
        </div>
		
	    <div id="user_nav" class="pull-right">
	      <% if user_signed_in? %>
	        Logged in as <strong><%= current_user.email %></strong>.
	        <%= link_to 'Edit profile', edit_user_registration_path %> |
	        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
	      <% else %>
	        <%= link_to "Sign up", new_user_registration_path %> |
	        <%= link_to "Login", new_user_session_path %>
	      <% end %>
	    </div>

	    <% flash.each do |name, msg| %>
			<div class="container pull-left">
			    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
			      <a class="close" data-dismiss="alert">x</a>
			      <%= msg  %>
			    </div>
			</div>
	    <% end %>
		
		
      </div>
    </div>

    <div class="container-fluid">
 		
        <%= yield %>

      <footer>
		<hr>
        <p>&copy; <%= Time.now.year %> Terri Wise &amp; Ezra Ball</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

  </body>
</html>